# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "horizon.vortex.labels" $ | nindent 4 }}
type: Opaque
data:
  mongoUrl: {{ .Values.mongo.url | b64enc | quote }}

