# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vortex
  labels: {{ include "horizon.vortex.labels" $ | nindent 4 }}
spec:
  selector: {{ include "horizon.vortex.selector" $ | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
  # Setting clusterIP to None means no fixed Cluster-IP is assigned.
  clusterIP: None
{{- end }}
