# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# -- Deployment Configuration --

# -- Sets the number of replicas for the deployment.
replicaCount: 1

# -- Specifies the image details such as repository, tag, and pull policy.
image:
  repository: registry.example.domain.com/horizon/vortex
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: develop

# -- List of pull secrets that are required for pulling the the container images.
imagePullSecrets: []

nameOverride: vortex
fullnameOverride: ""

extraLabels:
  app.kubernetes.io/component: event-sourcing
  app.kubernetes.io/part-of: horizon-runtime
  ei.telekom.de/product: horizon
  ei.telekom.de/platform: o28m
  ei.telekom.de/environment: integration
  ei.telekom.de/zone: aws

# -- RBAC (Role-Based Access Control) specific configuration.
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Specifies the annotationsfor the pod.
podAnnotations: {}
# -- Specifies the labels for the pod.
podLabels: {}

# -- Security context set for the pod.
podSecurityContext:
  fsGroup: 1000
  supplementalGroups: [1000]

# -- Security context set for the container.
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop:
    - ALL

# -- Specifies the service type and port as well as the labels for the service.
service:
  type: ClusterIP
  port: http
  labels:
    ei.telekom.de/product: horizon
    ei.telekom.de/environment: integration

# -- Specifies whether ingress is enabled, sets the hostname(s) and Ingress annotations.
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Resource limits and requests.
resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 200Mi

# -- Kubernetes Liveness Probe configuration.
livenessProbe:
#  httpGet:
#    path: /health
#    port: http
#  initialDelaySeconds: 20
#  periodSeconds: 10
#  failureThreshold: 8
# -- Kubernetes Readiness Probe configuration.
readinessProbe:
#  httpGet:
#    path: /health
#    port: http
#  initialDelaySeconds: 20
#  periodSeconds: 10
#  failureThreshold: 8
# -- Kubernetes Startup Probe configuration.
startupProbe:
#  httpGet:
#    path: /health
#    port: http
#  initialDelaySeconds: 0
#  periodSeconds: 1
#  failureThreshold: 75

lifecycle:
#  preStop:
#    httpGet:
#      path: /shutdown
#      port: http
#      scheme: HTTP

# -- Horizontal Pod Autoscaler configuration.
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
- name: tmp
  emptyDir: {}
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- mountPath: /tmp
  name: tmp
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# Node selector for pod assignment.
nodeSelector: {}
# Tolerations for pod assignment.
tolerations: []
# Affinity for pod assignment.
affinity: {}

# -- ServiceMonitor configuration.
monitoring:
  serviceMonitor:
    enabled: true
    selector: selector
    targetLabels:
      - app.kubernetes.io/instance
      - ei.telekom.de/product
      - ei.telekom.de/environment
      - ei.telekom.de/zone

# -- Custom environment variables
customEnv: {}

# -- Logging: Sets the log level for general logging.
logLevel: INFO

# -- Kafka: Configuration for connecting to Kafka brokers and managing topics.
kafka:
  broker: kafka:9092
  groupname: vortex
  topics:
    - subscribed
    - subscribed_5d
    - subscribed_3d
    - subscribed_1d
    - subscribed_1h
  sessionTimeoutSec: 40

# -- MongoDB: Configuration for connecting to MongoDB database and managing collection, bulkSize and flushIntervalSec.
mongo:
  url: mongodbUrl
  database: horizon
  collection: status
  bulkSize: 500
  flushIntervalSec: 30

# -- Metrics: Vortex metrics configuration.
metrics:
  enabled: false
  port: 8080
  release: release
