# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceAccount.create }}
{{- $name := include "horizon.comet.serviceAccountName" . }}
{{- $roleKind := "Role" }}
{{- $roleBindingNamespace := default .Release.Namespace .Values.commonHorizon.informer.namespace }}
{{- if ne $roleBindingNamespace .Release.Namespace }}
{{- $roleKind = "ClusterRole" }}
{{- end }}
# --- Service Account Configuration ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
---
# --- Role Configuration for RBAC ---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleKind }}
metadata:
  name: {{ $name }}
rules:
- apiGroups:
  - subscriber.horizon.telekom.de
  resources:
  - subscriptions
  verbs:
  - get
  - list
  - watch
---
# --- Role Binding Configuration for RBAC ---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $roleBindingNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $roleKind }}
  name: {{ $name }}
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
{{- end }}