# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# -- Deployment Configuration --

# -- Sets the number of replicas for the deployment.
replicaCount: 1

# -- Specifies the image details such as repository, tag, and pull policy.
image:
  repository: registry.example.domain.com/horizon/galaxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: develop

# -- List of pull secrets that are required for pulling the the container images.
imagePullSecrets: []

nameOverride: galaxy
fullnameOverride: ""

extraLabels:
  app.kubernetes.io/component: event-handler
  app.kubernetes.io/part-of: horizon
  ei.telekom.de/product: horizon
  ei.telekom.de/platform: o28m
  ei.telekom.de/environment: integration
  ei.telekom.de/zone: aws

# -- RBAC (Role-Based Access Control) specific configuration.
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Specifies the annotationsfor the pod.
podAnnotations: {}
# -- Specifies the labels for the pod.
podLabels:
  ei.telekom.de/pubsub-horizon-cache-context: galaxy

# -- Security context set for the pod.
podSecurityContext:
  fsGroup: 1000
  supplementalGroups: [1000]

# -- Security context set for the container.
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
    - ALL

# -- Specifies the service type and port as well as the labels for the service.
service:
  type: ClusterIP
  port: http
  labels:
    ei.telekom.de/product: horizon
    ei.telekom.de/environment: integration

# -- Specifies whether ingress is enabled, sets the hostname(s) and Ingress annotations.
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Resource limits and requests.
resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 200Mi

# -- Kubernetes Liveness Probe configuration.
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 8
# -- Kubernetes Readiness Probe configuration.
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 8
# -- Kubernetes Startup Probe configuration.
startupProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 75

lifecycle:
#  preStop:
#    httpGet:
#      path: /actuator/shutdown
#      port: http
#      scheme: HTTP

# -- Horizontal Pod Autoscaler configuration.
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
- name: tmp
  emptyDir: {}
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- mountPath: /tmp
  name: tmp
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# Node selector for pod assignment.
nodeSelector: {}
# Tolerations for pod assignment.
tolerations: []
# Affinity for pod assignment.
affinity: {}

# -- ServiceMonitor configuration.
monitoring:
  serviceMonitor:
    enabled: true
    selector: selector
    targetLabels:
      - app.kubernetes.io/instance
      - ei.telekom.de/product
      - ei.telekom.de/environment
      - ei.telekom.de/zone

# -- Custom environment variables
customEnv: {}

commonHorizon:
  # -- Sets the issuerUrl that is used for authentication.
  issuerUrl: https://keycloak.example.domain.com/auth/realms/example

  # -- Specifies Kafka broker details for common Horizon settings, including broker addresses, groupId, linger time, acknowledgment settings, and compression options.
  kafka:
    brokers: kafka:9092
    groupId: galaxy
    lingerMs: 5
    acks: 1
    compression:
      enabled: true
      type: snappy

  # -- Specifies namespace for the informer that watches the custom resources.
  informer:
    namespace: default

  # -- Sets the default environment.
  defaultEnvironment: default

  # -- Sets the timeout duration (in milliseconds) for the publishing process.
  publishingTimeoutMs: 45000

  # -- Sets the log level for general logging.
  logLevel: WARN

  # -- Configures tracing settings, including debug mode, Jaeger collector base URL, and sampler probability.
  tracing:
    debugEnabled: false
    jaegerCollectorBaseUrl: http://localhost:14268
    samplerProbability: "1.0"

  # -- Enables or disables JMX remote configuration.
  jmxRemote:
    enabled: false

galaxy:
  # -- Kafka configuration for "galaxy" component: Specifies Kafka consumer settings for the "galaxy" component, such as consumingTopic, consumingGroupId and consumingPartitionCount.
  kafka:
    consumingTopic: published
    consumingGroupId: galaxy
    consumingPartitionCount: 16

  # -- CoreThreadPoolSize: Specifies the core size of the thread pool.
  coreThreadpoolSize: 5

  # -- MaxThreadpoolSize: Specifies the maximum size of the thread pool.
  maxThreadpoolSize: 100

  # -- MaxTimeout:  Specifies the maximum timeout value in milliseconds for operations.
  maxTimeout: 100000

  # -- MaxRetries: Specifies the maximum number of retries allowed for operations.
  maxRetries: 10

  # -- Initial BackOffInterval: Specifies the initial backoff interval in milliseconds for retry operations.
  initialBackoffInterval: 100

  # -- MaxBackOffInterval: Specifies the maximum backoff interval in milliseconds for retry operations.
  maxBackoffInterval: 30000

  # -- BackoffMultiplier: Specifies the backoff multiplier used for exponential backoff in retry operations.
  backoffMultiplier: 2.0

  # -- ReseekInterval: Specifies the reseek interval in milliseconds.
  reseekInterval: "3600000"

  # -- Reprocessing: Configuration for reprocessing of messages.
  reprocessing:
    enabled: true
    maxRetries: 10
    maxUnbridgedMessageAgeMs: 180000
    reprocessIntervalMs: 300000

  # -- Cache configuration: Define cache service DNS.
  cache:
    serviceDns: cache