# -- Deployment Configuration --

# -- Image configuration for "pulsar" deployment: Specifies the image details such as repository, organization, name, tag, and pull policy.
image:
  repository: example.devops.company.de
  organization: internal/example/horizon
  name: pulsar
  tag: develop
  pullPolicy: IfNotPresent

# -- Deployment replicas: Sets the number of replicas for the deployment.
replicas: 1

common:
  # -- ImagePullSecrets: Defines image pull secrets for different clusters.
  imagePullSecrets: []
  cluster: cluster
  team: horizon-pubsub
  product: horizon
  subProduct: pulsar
  metadata:
    environment: default
  domain: example.domain.com

commonHorizon:
  # -- IssuerUrl: Sets the issuerUrl.
  issuerUrl: issuerUrl

  # -- Kafka configuration: Specifies Kafka broker details for common Horizon settings, including broker addresses, groupId, linger time, acknowledgment settings, and compression options.
  kafka:
    brokers: kafka:9092
    groupId: pulsar
    lingerMs: 5
    acks: 1
    compression:
      enabled: true
      type: snappy

  # -- Informer: Specifies namespace for the informer.
  informer:
    namespace: default

  # -- Environment: Sets the default environment.
  defaultEnvironment: default

  # -- Logging: Sets the log level for general logging.
  logLevel: WARN

  # -- Logging: Sets the log level for Horizon specific logging.
  horizonLogLevel: WARN

  # -- Tracing: Configures tracing settings, including Jaeger collector base URL, and sampler probability.
  tracing:
    jaegerCollectorBaseUrl: http://localhost:14268
    samplerProbability: "1.0"

  # -- JMX: Enables or disables JMX remote configuration.
  jmxRemote:
    enabled: false

# -- Affinity: Configures settings related to affinity.
affinity:
  enabled: true

# -- RBAC: Configures settings related to RBAC (Role-Based Access Control).
rbac:
  create: "true"
  serviceAccountName:

pulsar:
  # -- ThreadPoolSize: Specifies the size of the thread pool.
  threadPoolSize: 1000

  # -- QueueCapacity: Specifies the capacity of the queue.
  queueCapacity: 2000

  # -- SsePollDelay: Specifies the polling delay in milliseconds for Server-Sent Events (SSE).
  ssePollDelay: 1000

  # --SseTimeout: Specifies the timeout in milliseconds for Server-Sent Events (SSE).
  sseTimeout: 50000

  # -- SseBatchSize: Specifies the batch size for Server-Sent Events (SSE).
  sseBatchSize: 50

  # -- Oauth enabled: Enables or disables OAuth authentication.
  oauthEnabled: true

  # -- Mongo configuration: Enable mongo config and set clientId and mongo URL for mongo configuration.
  mongo:
    enabled: true
    clientId: pulsar
    url: mongodbUrl

  # -- Features: Enabled subscriberValidationCheck.
  features:
    subscriberCheck: true

  # -- Cache configuration: Enable cache data deduplication.
  cache:
    deDuplication:
      enabled: true

# -- Ingress: Specifies whether ingress is enabled, sets the hostname, annotations, and indicates whether it is designed for CaaS (Container as a Service).
ingress:
  #tlsSecret: ""
  enabled: false
  hostname:
  annotations: {}
  isCaaS: false

# -- Monitoring: ServiceMonitor configuration.
monitoring:
  serviceMonitor:
    enabled: true
    selector: selector

# -- LivenessProbe: Kubernetes Liveness Probe configuration.
livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 8

# -- ReadinessProbe: Kubernetes Readiness Probe configuration.
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 8

# -- StartupProbe: Kubernetes Startup Probe configuration.
startupProbe:
  enabled: false
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 75

# -- PodSecurityContext: Security context set for the pod.
podSecurityContext:
  fsGroup: 1000
  supplementalGroups: [1000]

# -- ContainerSecurityContext: Security context set for the container.
containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
    - ALL

# -- Resources: Resource limits and requests.
resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 200Mi
