apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo
  labels: {{ include "horizon.pulsar.labels" $ | nindent 4 }}
type: Opaque
data:
  mongoUrl: {{ .Values.pulsar.mongo.url | b64enc | quote }}
