# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pulsar
  labels:
  {{- include "horizon.pulsar.labels" $ | nindent 4 }}
  {{- include "common.statusmonitor.labels" $ | nindent 4 }}
spec:
  selector: {{ include "horizon.pulsar.selector" $ | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: actuator
      port: 8081
      targetPort: 8081
      protocol: TCP
