# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "horizon.pulsar.fullname" . }}
  labels: 
  {{- include "horizon.pulsar.labels" $ | nindent 4 }}
  {{- if eq (toString .Values.monitoring.serviceMonitor.enabled) "true" }}
  {{- with .Values.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  selector: {{ include "horizon.pulsar.selectorLabels" $ | nindent 4 }}
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: actuator
    port: 8081
    targetPort: 8081
    protocol: TCP
