# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

{{- if eq (toString .Values.monitoring.serviceMonitor.enabled) "true" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "horizon.starlight.fullname" . }}
  labels: {{ include "horizon.starlight.labels" $ | nindent 4 }}
    release: {{ .Values.monitoring.serviceMonitor.selector }}
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels: {{ include "horizon.starlight.selectorLabels" $ | nindent 6 }}
  endpoints:
    - port: actuator
      path: "/actuator/prometheus"
  targetLabels:
  {{- with .Values.monitoring.serviceMonitor.targetLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
