# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iris
  labels: {{ include "horizon.polaris.labels" $ | nindent 4 }}
type: Opaque
data:
  clientSecret: {{ .Values.polaris.iris.clientSecret | b64enc | quote }}