# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horizon.polaris.fullname" . }}
  labels: {{ include "horizon.polaris.labels" $ | nindent 4 }}
type: Opaque
data:
  mongoUrl: {{ .Values.polaris.mongo.url | b64enc | quote }}
  clientSecret: {{ .Values.polaris.iris.clientSecret | b64enc | quote }}