{{- if eq (toString .Values.monitoring.serviceMonitor.enabled) "true" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "horizon.polaris.labels" $ | nindent 4 }}
    release: {{ .Values.monitoring.serviceMonitor.selector }}
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels: {{ include "horizon.polaris.selector" $ | nindent 6 }}
  endpoints:
    - port: http
      path: "/actuator/prometheus"
  targetLabels:
    - developer.telekom.de/cluster
    - developer.telekom.de/namespace
    - developer.telekom.de/product
    - developer.telekom.de/subproduct
    - developer.telekom.de/team
    - developer.telekom.de/environment
    - app
{{- end -}}
