# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-polaris
  labels: 
  {{- include "horizon.polaris.labels" $ | nindent 4 }}
  {{- include "common.statusmonitor.labels" $ | nindent 4 }}
spec:
  selector: {{ include "horizon.polaris.selector" $ | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  # Setting clusterIP to None means no fixed Cluster-IP is assigned.
  clusterIP: None
