# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# -- Deployment Configuration --

# -- Sets the number of replicas for the deployment.
replicaCount: 1

# -- Specifies the image details such as repository, tag, and pull policy.
image:
  repository: registry.example.domain.com/horizon/comet
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: develop

# -- List of pull secrets that are required for pulling the the container images.
imagePullSecrets: []

nameOverride: comet
fullnameOverride: ""

extraLabels:
  app.kubernetes.io/component: callback-delivery
  app.kubernetes.io/part-of: horizon-runtime
  ei.telekom.de/product: horizon
  ei.telekom.de/platform: o28m
  ei.telekom.de/environment: integration
  ei.telekom.de/zone: aws

# -- RBAC (Role-Based Access Control) specific configuration.
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Specifies the annotationsfor the pod.
podAnnotations: {}
# -- Specifies the labels for the pod.
podLabels:
  ei.telekom.de/pubsub-horizon-cache-context: callback

# -- Security context set for the pod.
podSecurityContext:
  fsGroup: 1000
  supplementalGroups: [1000]

# -- Security context set for the container.
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
    - ALL

# -- Specifies the service type and port as well as the labels for the service.
service:
  type: ClusterIP
  port: http
  labels:
    ei.telekom.de/product: horizon
    ei.telekom.de/environment: integration

# -- Specifies whether ingress is enabled, sets the hostname(s) and Ingress annotations.
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Resource limits and requests.
resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 50m
    memory: 200Mi

# -- Kubernetes Liveness Probe configuration.
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 5
# -- Kubernetes Readiness Probe configuration.
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 5
# -- Kubernetes Startup Probe configuration.
startupProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 75

lifecycle:
#  preStop:
#    httpGet:
#      path: /actuator/shutdown
#      port: http
#      scheme: HTTP

# -- Horizontal Pod Autoscaler configuration.
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
- name: tmp
  emptyDir: {}
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- mountPath: /tmp
  name: tmp
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# Node selector for pod assignment.
nodeSelector: {}
# Tolerations for pod assignment.
tolerations: []
# Affinity for pod assignment.
affinity: {}

# -- ServiceMonitor configuration.
monitoring:
  serviceMonitor:
    enabled: true
    selector: selector
    targetLabels:
      - app.kubernetes.io/instance
      - ei.telekom.de/product
      - ei.telekom.de/environment
      - ei.telekom.de/zone

# -- Custom environment variables
customEnv: {}

commonHorizon:
  # -- Sets the issuerUrl that is used for authentication.
  issuerUrl: https://keycloak.example.domain.com/auth/realms/example

  # -- Specifies Kafka broker details for common Horizon settings, including broker addresses, groupId, linger time, acknowledgment settings, and compression options.
  kafka:
    brokers: kafka:9092
    groupId: comet
    lingerMs: 5
    acks: 1
    compression:
      enabled: true
      type: snappy

  # -- Specifies namespace for the informer that watches the custom resources.
  informer:
    namespace: default

  # -- Sets the default environment.
  defaultEnvironment: default

  # -- Sets the timeout duration (in milliseconds) for the publishing process.
  publishingTimeoutMs: 45000

  # -- Sets the log level for general logging.
  logLevel: WARN
  # -- Sets the log level for Horizon specific logging.
  horizonLogLevel: WARN

  # -- Configures tracing settings, including debug mode, Jaeger collector base URL, and sampler probability.
  tracing:
    debugEnabled: false
    jaegerCollectorBaseUrl: http://localhost:14268
    samplerProbability: "1.0"

  # -- Enables or disables JMX remote configuration.
  jmxRemote:
    enabled: false

comet:
  # -- Kafka configuration for "comet" component: Specifies Kafka details for the "comet" component, such as consumingGroupId, consumingPartitionCount, consumerThreadPoolSize, consumerQueueCapacity and maxPollRecords.
  kafka:
    consumingGroupId: comet
    consumingPartitionCount: 16
    consumerThreadpoolSize: 4096
    consumerQueueCapacity: 8192
    maxPollRecords: 500

  # -- Iris configuration: Authentication details for Iris, including the token endpoint, clientId, and client secret.
  iris:
    tokenEndpoint: irisUrl
    clientId: clientId
    clientSecret: secret

  # -- Callback configuration: Configures parameters for callback handling, including timeouts, retries, backoff intervals, connection limits, and status codes for success and redelivery.
  callback:
    maxTimeout: 30000
    maxRetries: 10
    initialBackoffIntervalMs: 100
    maxBackoffIntervalMs: 60000
    backoffMultiplier: 2.0
    maxConnections: 1000
    successfulStatusCodes: 200,201,202,204
    redeliveryStatusCodes: 401,429,502,503,504
    redeliveryQueueCapacity: 2048
    redeliveryThreadpoolSize: 16

  # -- Security configuration: Set timeouts for secure token retrieval.
  security:
    retrieveTokenConnectTimeout: 5000
    retrieveTokenReadTimeout: 5000

  # -- Cache configuration: Define cache service DNS and enable data deduplication.
  cache:
    serviceDNS: app-cache-headless.integration.svc.cluster.local
    deDuplication:
      enabled: true