# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horizon.starlight.fullname" . }}
  labels: {{ include "horizon.starlight.labels" $ | nindent 4 }}
type: Opaque
data:
  eniApiClientId: {{ .Values.starlight.eniapi.auth.clientId | b64enc | quote }}
  eniApiClientSecret: {{ .Values.starlight.eniapi.auth.clientSecret | b64enc | quote }}
  