name: Publish Helm Charts

on:
  push:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chart:
          - horizon-starlight
          - horizon-galaxy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get current branch
        id: refs
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          echo "branch=$branch" >> $GITHUB_OUTPUT

      - name: Read chart version
        id: chart_version
        run: |
          version=$(grep '^version:' ./${{ matrix.chart }}/Chart.yaml | awk '{print $2}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Run semantic-release on main
        if: steps.refs.outputs.branch == 'main'
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set chart tag
        id: chart_tag
        run: |
          if [ "${{ steps.refs.outputs.branch }}" = "main" ]; then
            tag="${{ steps.chart_version.outputs.version }}"
          else
            sanitized=$(echo "${{ steps.refs.outputs.branch }}" | tr '/_' '--')  # replace / and _ with hyphens
            tag="${{ steps.chart_version.outputs.version }}-${sanitized}"
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Push chart to OCI
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: ${{ matrix.chart }}
          repository: ${{ github.repository_owner }}
          tag: ${{ steps.chart_tag.outputs.tag }}
          path: ${{ matrix.chart }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
