# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Helm Charts

on:
  push:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get current branch
        id: refs
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Run semantic-release on main
        if: steps.refs.outputs.branch == 'main'
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Discover charts
        id: charts
        run: |
          charts=$(find charts -name Chart.yaml -exec dirname {} \; | sed 's|charts/||')
          json=$(printf '%s\n' $charts | jq -R . | jq -cs .)
          echo "charts=$json" >> $GITHUB_OUTPUT

      - name: Push Helm charts to OCI
        run: |
          charts=$(echo '${{ steps.charts.outputs.charts }}' | jq -r '.[]')
          for chart in $charts; do
            chart_path="charts/$chart"
            version=$(grep '^version:' "$chart_path/Chart.yaml" | awk '{print $2}')

            if [ "${{ steps.refs.outputs.branch }}" = "main" ]; then
              tag="$version"
            else
              sanitized=$(echo "${{ steps.refs.outputs.branch }}" | tr '/_' '-')
              tag="${version}-${sanitized}"
            fi

            echo "Pushing chart $chart with tag $tag"
            helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            helm dependency update "$chart_path"
            helm package "$chart_path" --version "$tag"
            helm push "$chart-$tag.tgz" oci://ghcr.io/pubsub
          done

